export const ROUTES = {
  LOGIN: "/login",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  CUSTOMERS_NEW: "/customers/new",
  SITES: "/sites",
  JOBS: "/jobs",
  AGREEMENTS: "/agreements",
  QUOTES: "/quotes",
  QUOTES_NEW: "/quotes/new",
  CALENDAR: "/calendar",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  AUTH_CALLBACK: "/auth/callback",

  customerDetail: (id: string) => `/customers/${id}` as const,
  customerEdit: (id: string) => `/customers/${id}/edit` as const,
  siteDetail: (id: string) => `/sites/${id}` as const,
  siteEdit: (id: string) => `/sites/${id}/edit` as const,
  jobDetail: (id: string) => `/jobs/${id}` as const,
  quoteDetail: (id: string) => `/quotes/${id}` as const,
} as const;
