/**
 * Generates the GEM Services PDF footer band as a font-independent image.
 *
 * Why an image: Puppeteer's footerTemplate (the only thing that pins a footer
 * to the bottom of EVERY page incl. a partial last page) renders in a separate
 * context where an embedded @font-face does NOT load (Montserrat falls back to
 * serif) and backgrounds are flaky. Baking the band into one image sidesteps
 * both — exact Montserrat + exact #9AC44B, reliably.
 *
 * Source of truth = FOOTER_CONTACT (lib/constants/branding.ts). After editing
 * it, regenerate:   npx tsx scripts/generate-footer-band.ts
 *
 * Outputs (both committed, alongside the logo):
 *   - public/logo/footer-band.png   — the visual asset (human-viewable)
 *   - lib/pdf/footer-band.ts        — base64 data URI + aspect, imported by
 *                                     htmlToPdf (no runtime file read → no
 *                                     outputFileTracingIncludes dependency).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { MONTSERRAT_FACE_CSS } from "../lib/pdf/assets";
import { FOOTER_CONTACT } from "../lib/constants/branding";

// Render width in px; the band is displayed at full A4 width (210mm) in the
// PDF, so only the ASPECT ratio matters for final sizing.
const W = 2100;

const html = `<!DOCTYPE html><html><head><meta charset="utf-8" /><style>
  ${MONTSERRAT_FACE_CSS}
  *{margin:0;padding:0;box-sizing:border-box}
  html,body{margin:0;background:#fff}
  #band{
    width:${W}px;
    background:#9AC44B;
    color:#fff;
    font-family:'Montserrat',sans-serif;
    text-align:center;
    padding:30px 120px;
  }
  .l1{font-size:27px;font-weight:600;line-height:1.55;letter-spacing:.3px}
  .l2{font-size:22px;font-weight:400;line-height:1.5;opacity:.92;margin-top:3px}
  .sep{opacity:.6;margin:0 18px;font-size:18px;vertical-align:middle}
</style></head><body>
  <div id="band">
    <div class="l1">${FOOTER_CONTACT.phone}<span class="sep">&#9670;</span>${FOOTER_CONTACT.email}<span class="sep">&#9670;</span>${FOOTER_CONTACT.website}</div>
    <div class="l2">${FOOTER_CONTACT.legal}</div>
  </div>
</body></html>`;

async function main() {
  const puppeteer = await import("puppeteer");
  const browser = await puppeteer.default.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  const page = await browser.newPage();
  await page.setViewport({ width: W, height: 600, deviceScaleFactor: 2 });
  await page.setContent(html, { waitUntil: "load" });
  await page.evaluate(async () => {
    await (document as unknown as { fonts: { ready: Promise<unknown> } }).fonts.ready;
  });
  const el = await page.$("#band");
  if (!el) throw new Error("band element not found");
  const box = await el.boundingBox();
  const buf = Buffer.from(await el.screenshot({ type: "png" }));
  await browser.close();
  if (!box) throw new Error("no bounding box");

  const aspect = box.height / box.width;
  const root = process.cwd();
  writeFileSync(join(root, "public/logo/footer-band.png"), buf);
  writeFileSync(
    join(root, "lib/pdf/footer-band.ts"),
    `// GENERATED by scripts/generate-footer-band.ts — DO NOT EDIT BY HAND.
// Regenerate after editing FOOTER_CONTACT (lib/constants/branding.ts):
//   npx tsx scripts/generate-footer-band.ts
// Full-width #9AC44B band, white Montserrat text — base64-inlined into
// htmlToPdf's footerTemplate (no runtime file read). The aspect (height /
// width) drives the reserved bottom page margin so the band fills it exactly.
export const FOOTER_BAND_ASPECT = ${aspect.toFixed(6)};
export const FOOTER_BAND_DATA_URI =
  "data:image/png;base64,${buf.toString("base64")}";
`
  );
  console.log(
    `band ${box.width}x${box.height}px | aspect ${aspect.toFixed(
      4
    )} | at 210mm -> ${(210 * aspect).toFixed(1)}mm tall | png ${buf.length} bytes`
  );
}

main();
